### ISSUE TITLE
Python script for command handling

### ISSUE THREAD

**Issue by MikeThomas-Dev** [Strizzi12/Drone_Communication#7]
Extend command algorithm for land and start so these commands will be processed before any new command gets executed.

**Comment by Strizzi12** [comment]
A flag for "Drone started" could help. 
So the "control commands" can only be executed if the flag "drone started" is set.

**Comment by MikeThomas-Dev** [comment]
This kind of flag would influence the start/control but not the land which is currently more important in my opinion. 
We would need some system to ensure a land command is computed asap and without interruption.
